### ISSUE TITLE
The json data source in license-list-data is missing the isFsfLibre attribute

### ISSUE THREAD

**Issue by nkolev92** [spdx/LicenseListPublisher#102]
Compare: https://raw.githubusercontent.com/spdx/license-list-data/master/rdfnt/licenses.nt to https://raw.githubusercontent.com/spdx/license-list-data/master/json/licenses.json. 

Take a license that's consider libre such as `Intel`, https://spdx.org/licenses/.

Note that the data is missing.

The NuGet client uses the json format as a source of truth for licenses, but now that's generating data based on an incomplete data source. 

https://github.com/NuGet/NuGet.Client/pull/4022

The change was made in https://github.com/spdx/license-list-data/commit/b8d6af45ad2fcfed61bb85a8ad068aa4a77eadf9.

**Comment by goneall** [comment]
@nkolev92 I see missing isFsfLibre flag from the licenses.json file.  Is that the only data you see missing?

Just a note - the licenses.json file only contains a summary of the information (e.g. it does not include the license text).

To get the full set of details, reference the license json file in the details folder - for example https://github.com/spdx/license-list-data/blob/master/json/details/Intel.json

I checked and the fsfLibre is present there.

I will look into adding the fsfLibre to the licenses file, however, since we do that for other similar flags (e.g. isOsiApproved).

**Comment by nkolev92** [comment]
Thanks for the quick response!


>  I see missing isFsfLibre flag from the licenses.json file. Is that the only data you see missing?

Yes. We use isFsfLibre, isOsiApproved and isDeprecatedLicenseId.

> Just a note - the licenses.json file only contains a summary of the information (e.g. it does not include the license text).

Yep, client side we just need the available license ids and their status. 
Server side, we use the full license text, but we have not run into issues there afaik.

> I will look into adding the fsfLibre to the licenses file, however, since we do that for other similar flags (e.g. isOsiApproved).

Perfect! That's exactly what we neeed. 

Thanks!

**Comment by goneall** [comment]
I created a pull request for the Java library.

@nkolev92 Attached is the resultant licenses.json file with the additional fields.  If you could review and let me know if this resolves the issue.

[licenses.json.txt](https://github.com/spdx/LicenseListPublisher/files/6388585/licenses.json.txt)

**Comment by nkolev92** [comment]
> I created a pull request for the Java library.
> 
> @nkolev92 Attached is the resultant licenses.json file with the additional fields. If you could review and let me know if this resolves the issue.
> 
> [licenses.json.txt](https://github.com/spdx/LicenseListPublisher/files/6388585/licenses.json.txt)

That works great. The data is just as expected.
