### ISSUE TITLE
Do not warn of duplicate deprecated licenses

### ISSUE THREAD

**Issue by goneall** [spdx/LicenseListPublisher#131]
If one or both of a license comparison is marked as duplicate, do not warn of the duplication as it is very likely expected.

This would make it easier to maintain the [expected-warnings](https://github.com/spdx/license-list-XML/blob/master/expected-warnings) file in the license-list-XML repo.

**Comment by goneall** [comment]
@swinslow @jlovejoy Let me know what you think about this enhancement.  On the positive side, it would reduce the number of times we would have to update the expected-warnings file.  On the negative side, we still may want to flag duplicates even if one of the licenses is deprecated.

**Comment by swinslow** [comment]
Hi @goneall -- just to understand, is the idea that if either of the licenses in a comparison is deprecated, then it just won't warn about duplicates for that particular pair?

If so, I think I'm good with that, actually. Seems like a clean and straightforward way to cut down on the warnings. If there's a duplicate with a deprecated license ID, then it isn't really a problem (and is probably intentional) because folks shouldn't be using the deprecated ID anyway.

**Comment by goneall** [comment]
> just to understand, is the idea that if either of the licenses in a comparison is deprecated, then it just won't warn about duplicates for that particular pair?

@swinslow - exactly

Unless there is any other objections, I'll implement over the next week or two

**Comment by goneall** [comment]
Hmmm - it looks like there is already a check for deprecated licenses.  However, in https://github.com/spdx/license-list-XML/pull/1446 there is clearly a warning generated for duplicate license text for deprecated licenses.

This may not be as simple - but something I'll look.

**Comment by goneall** [comment]
I just verified that there are no deprecated licenses in the warnings list - closing this issue
