### ISSUE TITLE
Inconsistent URLs for licenses vs exceptions

### ISSUE THREAD

**Issue by DennisClark** [spdx/LicenseListPublisher#170]
Something appears to have changed in the SPDX license list web pages. For example, 
https://spdx.org/licenses/OpenJDK-assembly-exception-1.0.html is valid but
https://spdx.org/licenses/OpenJDK-assembly-exception-1.0 is no longer valid and one gets a 404 from it. This appears to be a problem for all exceptions.

Oddly enough, the problem is only with exceptions.
https://spdx.org/licenses/Apache-2.0 is valid AND
https://spdx.org/licenses/Apache-2.0.html is valid.

I am reasonably sure that the `.html` suffix was previously not required for exceptions but I am not able to specify a date when that stopped working.  Please investigate.

**Comment by goneall** [comment]
I looked at the generated files and indeed the publisher is not generating the HTML without the ".html" extension.

The issue is in the [SpdxWebsiteFormatWriter.java](https://github.com/spdx/LicenseListPublisher/blob/master/src/org/spdx/licenselistpublisher/licensegenerator/SpdxWebsiteFormatWriter.java) file.

It doesn't look like it was changed for over 2 years, so if it did work previously, it was probably 2 or more years ago.

I did create a pull which fixes the issue.

@DennisClark - do you think this is important enough to spin create a new release before the next license list update?

**Comment by DennisClark** [comment]
@goneall    I will let you decide how important it is, and thanks very much for addressing it!
